services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Authentication\:
        resource: '../../src/Authentication/'
        exclude:
            - '../../src/Authentication/Domain/Model/'
            - '../../src/Authentication/Domain/Event/'
            - '../../src/Authentication/Domain/Exception/'
            - '../../src/Authentication/Contract/Dto/'
            - '../../src/Authentication/Contract/Event/'
            - '../../src/Authentication/Infrastructure/Persistence/Entity/'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
