services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Driver\:
        resource: '../../src/Driver/'
        exclude:
            - '../../src/Driver/Domain/Model/'
            - '../../src/Driver/Domain/Event/'
            - '../../src/Driver/Domain/Exception/'
            - '../../src/Driver/Contract/Dto/'
            - '../../src/Driver/Contract/Event/'
            - '../../src/Driver/Infrastructure/Persistence/Entity/'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
