services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Penalty\:
        resource: '../../src/Penalty/'
        exclude:
            - '../../src/Penalty/Domain/Model/'
            - '../../src/Penalty/Domain/Event/'
            - '../../src/Penalty/Domain/Exception/'
            - '../../src/Penalty/Contract/Dto/'
            - '../../src/Penalty/Contract/Event/'
            - '../../src/Penalty/Infrastructure/Persistence/Entity/'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
