; Dev only. Enable per container with XDEBUG_MODE=debug (or develop,debug,...).
xdebug.mode = ${XDEBUG_MODE}
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.start_with_request = yes
