<?php

declare(strict_types=1);

/**
 * Generates deptrac.yaml from the module folders in src/ (everything except SharedKernel).
 * Run `make deptrac-generate` after adding a module, and commit the result.
 */

use Symfony\Component\Yaml\Yaml;

require dirname(__DIR__, 2).'/vendor/autoload.php';

$root = dirname(__DIR__, 2);
$modules = [];
foreach (glob($root.'/src/*', GLOB_ONLYDIR) ?: [] as $dir) {
    $name = basename($dir);
    if ('SharedKernel' !== $name) {
        $modules[] = $name;
    }
}
sort($modules);

$layerNames = ['Domain', 'Application', 'Contract', 'Infrastructure'];
$sharedKernel = array_map(static fn (string $layer): string => 'SharedKernel'.$layer, $layerNames);

$layers = [];
foreach (array_merge($modules, ['SharedKernel']) as $module) {
    foreach ($layerNames as $layer) {
        $layers[] = [
            'name' => $module.$layer,
            'collectors' => [['type' => 'directory', 'value' => sprintf('src/%s/%s/.*', $module, $layer)]],
        ];
    }
}
$layers[] = [
    'name' => 'Vendor',
    'collectors' => [[
        'type' => 'bool',
        'must' => [['type' => 'classNameRegex', 'value' => '/.*/']],
        'must_not' => [
            ['type' => 'classNameRegex', 'value' => '/^App\\\\/'],
            ['type' => 'php_internal', 'value' => '.*'],
        ],
    ]],
];

$ruleset = [];
foreach ($modules as $module) {
    $otherContracts = array_map(
        static fn (string $other): string => $other.'Contract',
        array_values(array_filter($modules, static fn (string $other): bool => $other !== $module)),
    );

    $ruleset[$module.'Domain'] = ['SharedKernelDomain'];
    $ruleset[$module.'Application'] = array_merge(
        [$module.'Domain', $module.'Contract', 'SharedKernelDomain', 'SharedKernelApplication', 'SharedKernelContract'],
        $otherContracts,
    );
    $ruleset[$module.'Contract'] = ['SharedKernelContract'];
    $ruleset[$module.'Infrastructure'] = array_merge(
        [$module.'Domain', $module.'Application', $module.'Contract'],
        $sharedKernel,
        $otherContracts,
        ['Vendor'],
    );
}
$ruleset['SharedKernelDomain'] = [];
$ruleset['SharedKernelApplication'] = ['SharedKernelDomain', 'SharedKernelContract'];
$ruleset['SharedKernelContract'] = [];
$ruleset['SharedKernelInfrastructure'] = ['SharedKernelDomain', 'SharedKernelApplication', 'SharedKernelContract', 'Vendor'];

$config = [
    'deptrac' => [
        'paths' => ['./src'],
        'exclude_files' => [],
        'layers' => $layers,
        'ruleset' => $ruleset,
        // Must stay empty: fix the code, not the rules.
        'skip_violations' => [],
    ],
];

$yaml = Yaml::dump($config, 8, 2);
$yaml = preg_replace('/^(\s*(?:exclude_files|skip_violations)): \{\s*\}$/m', '$1: []', $yaml) ?? $yaml;

file_put_contents(
    $root.'/deptrac.yaml',
    "# GENERATED by tools/deptrac/generate.php (make deptrac-generate). Do not edit by hand.\n".$yaml,
);
