<?php

declare(strict_types=1);

namespace Migrations\Messenger;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001000014 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the Messenger Doctrine transport table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger.messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_37AB5A9FB7336F0E3BD61CE16BA31DBBF396750 ON messenger.messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger.messenger_messages');
    }
}
